### ISSUE TITLE
恢复个人资料页面的用户名显示

### ISSUE THREAD

**Issue by cherinyy** [8qwe24657913/showTiebaUserName#1]
例子: https://tieba.baidu.com/home/main/?un=%E4%B8%AD%E5%8D%88%E4%BA%BA&ie=utf-8

目前百度取消了个人资料页面的用户名显示，请问可以加回来吗？

**Comment by 8qwe24657913** [comment]
抱歉这么长时间没看到，脚本已经更新，感谢反馈
